### ISSUE TITLE
Glowing text markdown glitch

### ISSUE THREAD

**Issue by TheodoreHua** [kfarnung/aoc-to-markdown#24]
On the AoC website, there is glowing text. It seems the extension turns the glowing text into italics. While this works for normal text, it seems to glitch on text in code blocks.

For example [this](https://lambda.sx/VrPG.png) on day 3 becomes [this](https://lambda.sx/zTS.png) in the markdown document.

**Comment by kfarnung** [comment]
I submitted an extension update to Google and Mozilla, it should hopefully be available shortly.
