### ISSUE TITLE
Partial glowing text in code block (related to #24)

### ISSUE THREAD

**Issue by TheodoreHua** [kfarnung/aoc-to-markdown#42]
The issue stated in #24 still happens when the glowing text is just a *part* of a code highlighting. For example today (Day 04, Part 1), ![this](https://img.theodorehua.dev/8KT1EQkT) shows as ![this](https://img.theodorehua.dev/TaxwJrnJ).

With how markdown works I'm pretty sure partial italic in a code block can't be achieved, but at the very least the syntax for it should be removed to have `188 * 24 = 4512` instead of `188 * 24 = _4512_`.

**Comment by kfarnung** [comment]
Submitted the update for review, looks like it's already published in the Firefox store, but still pending for Chrome and Edge.
